sudo: required
services:
  - docker

before_install:
  - docker build -t puvth/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true puvth/react-test npm test

after_success:
  - docker build -t puvth/multi-client  ./client
  - docker build -t puvth/multi-nginx ./nginx
  - docker build -t puvth/multi-server  ./server
  - docker build -t puvth/multi-worker  ./worker 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker  login -u  "$DOCKER_ID"  --password-stdin
  # Take those images and push them to docker hub
  - docker push puvth/multi-client
  - docker push puvth/multi-nginx
  - docker push puvth/multi-server
  - docker push puvth/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app:  multi-docker
  env:  MultiDocker-env
  bucket_name:  elasticbeanstalk-ap-southeast-1-106310245967
  bucket_path:  docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY